name: HappyCounsciousness
favicon: null
layout_spectrum: 0.37238874216564
typography_spectrum: 0.184647360118106
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#B8B42D'
    - '#697A21'
    - '#FFFCE8'
    - '#3E363F'
    - '#DD403A'
  brandStrength: 0.2807691760826856
  lightness: 0.18459558649919927
  saturation: 0.15509232552722096
  rhythmicContrast: 0.32947102445177734
purpose: []
